# -*- coding: utf-8 -*-
"""job_analysising_pandas_numpy.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11a6OokCxXeljlN9mJRnU1_HgwOaVy1zk
"""

import pandas as pd

df = pd.read_csv("data.csv")

print(type(df))

df.head()

df.columns

df.shape

df.info()

df.isnull().sum()

df["Job Title"].value_counts().head(10)

df["Description"].head()

skills = ["Python", "SQL", "Excel", "Power BI", "Tableau", "Pandas", "NumPy"]

for skill in skills:
    count = df["Description"].str.contains(skill, case=False, na=False).sum()
    print(f"{skill}: {count}")

skill_counts = {}

for skill in skills:
    skill_counts[skill] = df["Description"].str.contains(skill, case=False, na=False).sum()

skill_df = pd.DataFrame(
    list(skill_counts.items()),
    columns=["Skill", "Count"]
)

skill_df

import matplotlib.pyplot as plt

skill_df.plot(
    x="Skill",
    y="Count",
    kind="bar"
)

plt.title("Most Demanded Data Analyst Skills")
plt.ylabel("Number of Jobs")
plt.show()

skill_df.sort_values(
    by="Count",
    ascending=False
)

skill_df.loc[skill_df["Count"].idxmax()]

skill_df.sort_values(by="Count", ascending=False).head(3)

#print("""
# This project analyzed 521 Data Analyst job postings to identify the most in-demand skills.

# The analysis revealed that:
# - Excel (385 mentions)
# - SQL (314 mentions)
# - Python (195 mentions)

# Data visualization tools such as Tableau and Power BI also appeared frequently.

#Conclusion:
#Candidates aspiring to become Data Analysts should focus on Excel, SQL, Python, Tableau, and Power BI.
#""")